spring.application.name=filmout
logging.level.org.springframework.web=DEBUG
spring.mustache.suffix=.html
logging.level.es.urjc=TRACE

# recargar plantillas sin reiniciar
spring.thymeleaf.cache=false

# configuracion de la base de datos h2 en memoria disfrazada de mysql
spring.datasource.url=jdbc:h2:file:./basededatos_local;AUTO_SERVER=TRUE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# configuracion de hibernate para creacion de tablas
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# habilitar la consola web de h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# inicializacion de datos sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
